import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import Nav from "./components/shared/Nav";
import WorkOutProvider from "@/context/WorkOutProvider";
import { ToastContainer } from "react-toastify";
import Footer from "./components/shared/Footer";

// Font configurations
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "WorkOut Library-Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className={`${oswald.className} min-h-full flex flex-col`}>

          <WorkOutProvider>

            <Nav />
           {children}
            <Footer />
               
          
          </WorkOutProvider>

           <ToastContainer />
    

      </body>
    </html>
  );
}